# Generated by Django 3.1.4 on 2020-12-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='difficulty',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='trail_name',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='users',
        ),
        migrations.AddField(
            model_name='trail',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='directions',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='thumbnail',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='unique_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
