# Generated by Django 3.1.4 on 2020-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20201223_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
