# Generated by Django 3.1.4 on 2021-01-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_trail_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='users',
        ),
    ]
